In [4]:
import yfinance as yf

In [6]:
ticker = "BBDC4"
period = "5d"
ticker_obj = yf.Ticker(f"{ticker}.SA")

In [3]:
ticker_obj

yfinance.Ticker object <BBAS3.SA>

In [4]:
ticker_obj.history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-12-16 00:00:00-03:00,24.520000,24.600000,24.129999,24.160000,16061900,0.0,0.0
2024-12-17 00:00:00-03:00,24.250000,24.490000,24.010000,24.420000,27695800,0.0,0.0
2024-12-18 00:00:00-03:00,24.400000,24.400000,23.730000,23.740000,29428400,0.0,0.0
2024-12-19 00:00:00-03:00,23.809999,24.049999,23.750000,23.889999,16306300,0.0,0.0
2024-12-20 00:00:00-03:00,23.920000,24.139999,23.870001,24.080000,49200400,0.0,0.0
2024-12-23 00:00:00-03:00,24.070000,24.129999,23.879999,23.920000,12708100,0.0,0.0
2024-12-26 00:00:00-03:00,23.950001,24.400000,23.930000,24.200001,15208900,0.0,0.0
2024-12-27 00:00:00-03:00,24.340000,24.370001,24.110001,24.110001,10465000,0.0,0.0
2024-12-30 00:00:00-03:00,24.100000,24.330000,24.090000,24.170000,27146200,0.0,0.0
2025-01-02 00:00:00-03:00,24.170000,24.280001,23.840000,23.920000,14492900,0.0,0.0
2025-01-03 00:00:00-03:00,23.920000,24.059999,23.680000,23.740000,13778900,0.0,0.0
2025-01-06 00:00:00-03:00,23.980000,24.049999,23.809999,23.959999,12112300,0.0,0.0
2025-01-07 00:00:00-03:00,24.139999,24.379999,24.020000,24.250000,15724400,0.0,0.0
2025-01-08 00:00:00-03:00,24.230000,24.270000,23.950001,24.160000,16417000,0.0,0.0
2025-01-09 00:00:00-03:00,24.160000,24.270000,23.990000,24.270000,8286700,0.0,0.0
2025-01-10 00:00:00-03:00,24.250000,24.440001,24.129999,24.209999,17167200,0.0,0.0
2025-01-13 00:00:00-03:00,24.209999,24.430000,24.160000,24.209999,9941700,0.0,0.0
2025-01-14 00:00:00-03:00,24.250000,24.670000,24.170000,24.650000,18049200,0.0,0.0
2025-01-15 00:00:00-03:00,24.910000,25.000000,24.750000,24.940001,7053200,0.0,0.0

In [ ]:
ticker_obj.history(period=period)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-01-09 00:00:00-03:00,11.40,11.42,11.28,11.32,18386900,0.0,0.0
2025-01-10 00:00:00-03:00,11.32,11.33,11.07,11.18,46311500,0.0,0.0
2025-01-13 00:00:00-03:00,11.11,11.38,11.10,11.22,36560700,0.0,0.0
2025-01-14 00:00:00-03:00,11.23,11.49,11.06,11.43,43570500,0.0,0.0
2025-01-15 00:00:00-03:00,11.53,11.73,11.51,11.69,17498200,0.0,0.0

:

In [9]:
def retorna_cotacao(ticker, periodo="1mo"):
    ticker_obj = yf.Ticker(f"{ticker}.SA")
    hist = ticker_obj.history(period=periodo)["Close"]
    hist.index = hist.index.strftime("%Y-%m-%d")
    hist = round(hist, 2)
    # Limitar em 30 resultados
    if len(hist) > 30:
        slice_size = int(len(hist) / 30)
        hist = hist.iloc[::-slice_size][::-1]
    return hist.to_json()

In [10]:
hist = retorna_cotacao("BBAS3", "1y")
hist

'{"2024-01-18":25.53,"2024-01-30":25.94,"2024-02-09":26.56,"2024-02-23":26.47,"2024-03-06":27.19,"2024-03-18":26.03,"2024-03-28":26.31,"2024-04-10":26.76,"2024-04-22":25.45,"2024-05-03":26.22,"2024-05-15":25.69,"2024-05-27":25.47,"2024-06-07":25.26,"2024-06-19":25.02,"2024-07-01":25.1,"2024-07-11":25.22,"2024-07-23":25.69,"2024-08-02":24.91,"2024-08-14":26.6,"2024-08-26":27.43,"2024-09-05":28.32,"2024-09-17":27.66,"2024-09-27":26.55,"2024-10-09":25.75,"2024-10-21":25.94,"2024-10-31":25.66,"2024-11-12":25.29,"2024-11-26":25.49,"2024-12-06":24.56,"2024-12-18":23.74,"2025-01-03":23.74,"2025-01-15":24.94}'